name: test
recipe: lamp
config:
  webroot: public
  php: '7.4'
proxy:
  appserver:
    - test.local.lndo.site
services:
  database:
    portforward: 3306
  appserver:
    run_as_root:
      - a2enmod headers
      - apt update && apt install apt-transport-https gnupg2 locales -y
      - docker-php-ext-install sockets
      - echo "Europe/Amsterdam" > /etc/timezone
      - dpkg-reconfigure -f noninteractive tzdata
      - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
      - sed -i -e 's/# nl_NL.UTF-8 UTF-8/nl_NL.UTF-8 UTF-8/' /etc/locale.gen
      - echo 'LANG="nl_NL.UTF-8"'>/etc/default/locale
      - dpkg-reconfigure --frontend=noninteractive locales
      - update-locale LANG=nl_NL.UTF-8
      - curl -sL https://deb.nodesource.com/setup_10.x | bash -
      - apt update && apt install apt-transport-https gcc g++ make nodejs -y
      - service apache2 reload
events:
tooling:
  php:
    service: appserver
